In [38]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df.head(3)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138

In [12]:
type(df.index)

pandas.RangeIndex

In [15]:
type(df.columns)

pandas.Index

In [14]:
df.columns.to_list()

['entity', 'code', 'year', 'life_expectancy_0']

In [26]:
df.rename(columns={"entity": "País"}) #sirve para renombrar columnas en un DataFrame

              Pais code  year  life_expectancy_0
0      Afghanistan  AFG  1950            28.1563
1      Afghanistan  AFG  1951            28.5836
2      Afghanistan  AFG  1952            29.0138
3      Afghanistan  AFG  1953            29.4521
4      Afghanistan  AFG  1954            29.6975
...            ...  ...   ...                ...
21560     Zimbabwe  ZWE  2019            61.0603
21561     Zimbabwe  ZWE  2020            61.5300
21562     Zimbabwe  ZWE  2021            60.1347
21563     Zimbabwe  ZWE  2022            62.3601
21564     Zimbabwe  ZWE  2023            62.7748

[21565 rows x 4 columns]

In [ ]:
df.rename(columns={"entity": "País"},inplace=True) 
# Indica que la columna llamada entity ahora se llamará Pais. 
# "inplace=True" → Hace que el cambio se aplique directamente sobre el df, sin necesidad de crear una copia.

In [20]:
#df[df["entity"].str.contains("k", regex=True)] #Cadena de texto que contega la letra K

In [30]:
df.set_index("Pais")
#cambia el índice del DataFrame para que la columna "entity" se convierta en el índice principal.

            code  year  life_expectancy_0
Pais
Afghanistan  AFG  1950            28.1563
Afghanistan  AFG  1951            28.5836
Afghanistan  AFG  1952            29.0138
Afghanistan  AFG  1953            29.4521
Afghanistan  AFG  1954            29.6975
...          ...   ...                ...
Zimbabwe     ZWE  2019            61.0603
Zimbabwe     ZWE  2020            61.5300
Zimbabwe     ZWE  2021            60.1347
Zimbabwe     ZWE  2022            62.3601
Zimbabwe     ZWE  2023            62.7748

[21565 rows x 3 columns]

In [31]:
df.head(3)

          Pais code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138

In [ ]:
df.set_index(["code", "year"]) 
# se van a usar dos columnas (code y year) como índice compuesto

                  Pais  life_expectancy_0
code year
AFG  1950  Afghanistan            28.1563
     1951  Afghanistan            28.5836
     1952  Afghanistan            29.0138
     1953  Afghanistan            29.4521
     1954  Afghanistan            29.6975
...                ...                ...
ZWE  2019     Zimbabwe            61.0603
     2020     Zimbabwe            61.5300
     2021     Zimbabwe            60.1347
     2022     Zimbabwe            62.3601
     2023     Zimbabwe            62.7748

[21565 rows x 2 columns]

In [ ]:
df.loc[df["code"].isnull()] 
# selecciona todas las filas donde la columna code tiene valores nulos (NaN).

                                      entity code  year  life_expectancy_0
375                                 Americas  NaN  1770            34.8000
376                                 Americas  NaN  1830            34.8000
377                                 Americas  NaN  1850            35.1000
378                                 Americas  NaN  1870            35.1000
379                                 Americas  NaN  1900            41.0000
...                                      ...  ...   ...                ...
17703  Small Island Developing States (SIDS)  NaN  2019            72.0847
17704  Small Island Developing States (SIDS)  NaN  2020            71.7761
17705  Small Island Developing States (SIDS)  NaN  2021            69.8938
17706  Small Island Developing States (SIDS)  NaN  2022            72.1257
17707  Small Island Developing States (SIDS)  NaN  2023            72.7255

[1348 rows x 4 columns]

In [45]:
df.loc[df["code"].notnull(),["entity","year","life_expectancy_0"]].head() 
# df["code"].notnull() → genera una máscara booleana que es True en las filas donde la columna code no está vacía (no es NaN).
# df.loc[condición, columnas] → selecciona las filas que cumplen la condición y, además, solo muestra las columnas especificadas (entity, year, life_expectancy_0).

        entity  year  life_expectancy_0
0  Afghanistan  1950            28.1563
1  Afghanistan  1951            28.5836
2  Afghanistan  1952            29.0138
3  Afghanistan  1953            29.4521
4  Afghanistan  1954            29.6975

In [ ]:
df.dropna(subset=["code"], inplace=True)
# Elimina todas las filas donde la columna code está vacía (NaN).
# subset=["code"] → indica que solo se revisa la columna code para decidir si se borra la fila.
# inplace=True → el cambio se aplica directamente sobre el df, no devuelve una copia.

df.isnull().sum()
#Cuenta cuántos valores nulos (NaN) hay en cada columna.
#Devuelve una serie con el nombre de la columna y el número de valores faltantes.

entity               0
code                 0
year                 0
life_expectancy_0    0
dtype: int64

In [ ]:
df.shape
# devuelve una tupla (pareja) con el número de filas y columnas del df

(20217, 4)

In [ ]:
#Consulta
resultado = (
    df.groupby("entity")["life_expectancy_0"] #Agrupa el df por la columna entity 
    .mean() # Calcula el promedio de life_expectancy_0 para cada grupo.
    .sort_values(ascending=True)  # Ordena esos promedios de menor a mayor.
)
resultado.head(10) # Muestra las primeras 10 entidades con menor esperanza de vida promedio.

entity
USSR                        32.700000
South Sudan                 37.841631
Sierra Leone                43.189605
Mali                        43.760793
Niger                       44.187513
East Timor                  44.684692
Nigeria                     44.855897
Chad                        45.007786
Central African Republic    45.084431
Malawi                      45.554985
Name: life_expectancy_0, dtype: float64

In [ ]:
df_1980 = df[(df["year"] >= 1910) & (df["year"] <= 1910) ] ## Seleccionar un año del periodo historico
resultado = (
    df_1980.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado.head(10)

entity
Guatemala     24.0
Bolivia       28.0
Mexico        28.0
Paraguay      29.0
Venezuela     29.0
Chile         30.0
Kazakhstan    30.6
Colombia      31.0
Brazil        31.0
Costa Rica    33.0
Name: life_expectancy_0, dtype: float64